language: generic
sudo: no
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"
  - git clone -b copy-with-preserve-option https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install emacs-24.3-travis --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - evm install $EVM_EMACS --use --skip
  ## delete all the el files
  ## - find /tmp -name "*el"
  ## - find /tmp -name "*elc"
  ## - find /tmp -name "*elc" | sed 's/.$//' | xargs rm -f
  - cask
script:
  - emacs --version
  - make